import Head from 'next/head'
import BlogList from '../components/BlogList'
 


export default function Home({ blogs }) {
  return (
    <div>
      <Head>
        <title>My App Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlogList blogs={blogs} />

    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`http://localhost:1337/blogs`)
  const blogs = await res.json()

  return {
    props: {
      blogs
    }
  }
}

